### ISSUE TITLE
Windows builds missing?

### ISSUE THREAD

**Issue by roger-** [akehrer/fiddle#4]
The documentation suggests there are Windows builds available, but the link goes to the wiki and doesn't seem to include links to any binaries?

**Comment by akehrer** [comment]
@roger- The builds are available under [releases](https://github.com/akehrer/fiddle/releases). I'll update the wiki to point back to that for Windows users.

**Comment by roger-** [comment]
Ah, my bad.

Right now the READ says:

> available for each [release](https://github.com/akehrer/fiddle/wiki/Installation) in a ZIP archive

and you may want to chance the release link to point to the release page.
