### ISSUE TITLE
Request: drag and drop support

### ISSUE THREAD

**Issue by roger-** [akehrer/fiddle#6]
Does not appear to be support for this? (Tested in Windows 8.)

**Comment by akehrer** [comment]
No support for this, but it can be added.

@roger- are you thinking users should be allowed to drag files in to just the tab widget, or are there other areas the should accept drops as well?

**Comment by roger-** [comment]
Yeah I think dropping a file anywhere in the editor/tab widget should open it in a new tab.

**Comment by akehrer** [comment]
Should be working as of v0.4
